//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Prueba1Entities : DbContext
    {
        public Prueba1Entities()
            : base("name=Prueba1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bien> Bien { get; set; }
        public virtual DbSet<Detalle> Detalle { get; set; }
        public virtual DbSet<Ficha> Ficha { get; set; }
        public virtual DbSet<Responsable> Responsable { get; set; }
    
        public virtual ObjectResult<buscarSerie_Result> buscarSerie(string consulta, Nullable<int> cantidad)
        {
            var consultaParameter = consulta != null ?
                new ObjectParameter("consulta", consulta) :
                new ObjectParameter("consulta", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscarSerie_Result>("buscarSerie", consultaParameter, cantidadParameter);
        }
    }
}
