//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int Clave_D { get; set; }
        public int Ficha_Clave_F { get; set; }
        public int Bien_Clave_B { get; set; }
    
        public virtual Ficha Ficha { get; set; }
        public virtual Bien Bien { get; set; }
    }
}
