//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ficha()
        {
            this.Detalle = new HashSet<Detalle>();
        }
    
        public int Clave_F { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string TipoMovimiento { get; set; }
        public string ResponsableDelMovimiento { get; set; }
        public string Observacion { get; set; }
        public int Responsable_Clave_R { get; set; }
        public Nullable<int> TipoFicha { get; set; }
        public string CargoDeLaEpoca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalle { get; set; }
        public virtual Responsable Responsable { get; set; }
    }
}
